(define (problem basic)
  (:domain hotel)  (:objects r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
     h1 h2 h3 h4 h5 - habitacion
  )
  (:init
        (= (idhab h1) 1)
        (= (capacidad h1) 4)
        (= (idhab h2) 2)
        (= (capacidad h2) 4)
        (= (idhab h3) 3)
        (= (capacidad h3) 4)
        (= (idhab h4) 4)
        (= (capacidad h4) 4)
        (= (idhab h5) 5)
        (= (capacidad h5) 3)
        (pendiente r1)
        (= (idres r1) 1)
        (= (npers r1) 1)
        (= (dini r1) 1)
        (= (dfi r1) 10)
        (pendiente r2)
        (= (idres r2) 2)
        (= (npers r2) 1)
        (= (dini r2) 11)
        (= (dfi r2) 21)
        (pendiente r3)
        (= (idres r3) 3)
        (= (npers r3) 3)
        (= (dini r3) 1)
        (= (dfi r3) 10)
        (pendiente r4)
        (= (idres r4) 4)
        (= (npers r4) 3)
        (= (dini r4) 10)
        (= (dfi r4) 15)
        (pendiente r5)
        (= (idres r5) 5)
        (= (npers r5) 3)
        (= (dini r5) 11)
        (= (dfi r5) 17)
        (pendiente r6)
        (= (idres r6) 6)
        (= (npers r6) 3)
        (= (dini r6) 28)
        (= (dfi r6) 29)
        (pendiente r7)
        (= (idres r7) 7)
        (= (npers r7) 3)
        (= (dini r7) 1)
        (= (dfi r7) 20)
        (pendiente r8)
        (= (idres r8) 8)
        (= (npers r8) 3)
        (= (dini r8) 26)
        (= (dfi r8) 28)
        (pendiente r9)
        (= (idres r9) 9)
        (= (npers r9) 3)
        (= (dini r9) 28)
        (= (dfi r9) 29)
        (pendiente r10)
        (= (idres r10) 10)
        (= (npers r10) 3)
        (= (dini r10) 28)
        (= (dfi r10) 29)

        (= (coste) 0)
        (= (nplazas) 0)
        (= (nhab) 0)
      )
  (:goal
    (forall (?x - reserva )
        (not(pendiente ?x))
    )
  )
  (:metric minimize (+ (+(* 10 (nplazas)) (* 100 (nhab)) )(coste)) )
)

